import unittest
import time
import selenium.webdriver as webdriver
from selenium.webdriver.support.ui import Select
from homePage import HomePage
from loginPage import LoginPage
from managerHome import ManagerHomePage
from customerProfilePage import CustomerProfilePage
from addFlight import AddFlightPage
from updateFlight import UpdateFlightPage
from deleteFlight import DeleteFlightPage
from adminPage import AdminPage

import pytest

class TestLogin():
    @pytest.yield_fixture()
    def test_setup(self):
        print('Test Start')
        global driver
        driver=webdriver.Chrome('F:\dev\chromedriver.exe')
        yield
        driver.close()
        driver.quit()
        print('Test Completed')

    def test_01_login_valid(self,test_setup):
        driver.get('http://localhost:9090/WebSE/')

        home=HomePage(driver)
        home.clickSignIn()

        login=LoginPage(driver)
        time.sleep(1)
        login.selectUserType('Customer')
        time.sleep(1)
        login.enterEmail('mo@gmail.com')
        time.sleep(1)
        login.enterPassword('12345')
        time.sleep(1)
        login.signInClick()
        time.sleep(1)

    def test_02_Book_Flight(self,test_setup):
        driver.get('http://localhost:9090/WebSE/')

        home = HomePage(driver)
        home.clickSignIn()
        login = LoginPage(driver)
        time.sleep(1)
        login.selectUserType('Customer')
        time.sleep(1)
        login.enterEmail('mo@gmail.com')
        time.sleep(1)
        login.enterPassword('12345')
        time.sleep(1)
        login.signInClick()
        time.sleep(1)
        customer = CustomerProfilePage(driver)
        time.sleep(1)
        customer.enterDeparture('Vegas')
        time.sleep(1)
        customer.enterArrival('Bankok')
        time.sleep(1)
        customer.enterDate('12282019')
        time.sleep(1)
        customer.enterClass('Business')
        time.sleep(1)
        customer.enterAdultSeats(1)
        time.sleep(1)
        customer.enterChildrenSeats(2)
        time.sleep(1)
        customer.checkAvailabilty()
        time.sleep(2)

    def test_03_Add_Flight(self,test_setup):
        driver.get('http://localhost:9090/WebSE/')

        home = HomePage(driver)
        home.clickSignIn()
        login = LoginPage(driver)
        time.sleep(1)
        login.selectUserType('Manager')
        time.sleep(1)
        login.enterEmail('raja@gmail.com')
        time.sleep(1)
        login.enterPassword('1234')
        time.sleep(1)
        login.signInClick()
        time.sleep(1)
        manager=ManagerHomePage(driver)
        manager.addFlight()
        time.sleep(1)
        addflght=AddFlightPage(driver)
        addflght.enterFlightNo('1212D')
        time.sleep(1)
        addflght.enterDeparture('Bankok')
        time.sleep(1)
        addflght.enterArrival('Vegas')
        time.sleep(1)
        addflght.enterDate('12282019')
        time.sleep(1)
        addflght.enterTime('1227AM')
        time.sleep(1)
        addflght.enterEconomySeat(30)
        time.sleep(1)
        addflght.enterEconomyPrice(200)
        time.sleep(1)
        addflght.enterBusinessSeat(30)
        time.sleep(1)
        addflght.enterBusinessPrice(400)
        time.sleep(1)
        addflght.enterFirstSeat(20)
        time.sleep(1)
        addflght.enterFirstPrice(500)
        time.sleep(1)
        addflght.addFlight()
        time.sleep(2)

    def test_04_Accept_Request(self,test_setup):
        driver.get('http://localhost:9090/WebSE/')

        home = HomePage(driver)
        home.clickSignIn()

        login = LoginPage(driver)
        time.sleep(1)
        login.selectUserType('Admin')
        time.sleep(1)
        login.enterEmail('moeez@gmail.com')
        time.sleep(1)
        login.enterPassword('1234')
        time.sleep(1)
        login.signInClick()
        time.sleep(1)
        admin=AdminPage(driver)
        admin.selectApprove()
        time.sleep(1)
        admin.logout()
        time.sleep(1)

    def test_05_Update_Flight(self,test_setup):
        driver.get('http://localhost:9090/WebSE/')

        home = HomePage(driver)
        home.clickSignIn()
        login = LoginPage(driver)
        time.sleep(1)
        login.selectUserType('Manager')
        time.sleep(1)
        login.enterEmail('raja@gmail.com')
        time.sleep(1)
        login.enterPassword('1234')
        time.sleep(1)
        login.signInClick()
        time.sleep(1)
        manager=ManagerHomePage(driver)
        manager.updateFlight()
        time.sleep(1)
        updateflight=UpdateFlightPage(driver)
        updateflight.selectFlightNo('1212D')
        time.sleep(1)
        updateflight.enterDeparture('Bankok')
        time.sleep(1)
        updateflight.enterArrival('Vegas')
        time.sleep(1)
        updateflight.enterDate('12302019')
        time.sleep(1)
        updateflight.enterTime('1200AM')
        time.sleep(1)
        updateflight.enterEconomySeat(30)
        time.sleep(1)
        updateflight.enterEconomyPrice(200)
        time.sleep(1)
        updateflight.enterBusinessSeat(30)
        time.sleep(1)
        updateflight.enterBusinessPrice(400)
        time.sleep(1)
        updateflight.enterFirstSeat(20)
        time.sleep(1)
        updateflight.enterFirstPrice(500)
        time.sleep(1)
        updateflight.updateFlight()
        time.sleep(2)

    def test_06_Accept_Request(self,test_setup):
        driver.get('http://localhost:9090/WebSE/')

        home = HomePage(driver)
        home.clickSignIn()

        login = LoginPage(driver)
        time.sleep(1)
        login.selectUserType('Admin')
        time.sleep(1)
        login.enterEmail('moeez@gmail.com')
        time.sleep(1)
        login.enterPassword('1234')
        time.sleep(1)
        login.signInClick()
        time.sleep(1)
        admin=AdminPage(driver)
        admin.selectApprove()
        time.sleep(1)
        admin.logout()
        time.sleep(1)

    def test_07_Delete_Flight(self,test_setup):
        driver.get('http://localhost:9090/WebSE/')

        home = HomePage(driver)
        home.clickSignIn()
        login = LoginPage(driver)
        time.sleep(1)
        login.selectUserType('Manager')
        time.sleep(1)
        login.enterEmail('raja@gmail.com')
        time.sleep(1)
        login.enterPassword('1234')
        time.sleep(1)
        login.signInClick()
        time.sleep(1)
        manager=ManagerHomePage(driver)
        manager.deleteFlight()
        time.sleep(1)
        Deleteflight=DeleteFlightPage(driver)
        Deleteflight.selectFlightNo('1212D')
        time.sleep(1)
        Deleteflight.enterDate('12282019')
        time.sleep(1)
        Deleteflight.deleteFlight()
        time.sleep(2)

    def test_08_Accept_Request(self,test_setup):
        driver.get('http://localhost:9090/WebSE/')

        home = HomePage(driver)
        home.clickSignIn()

        login = LoginPage(driver)
        time.sleep(1)
        login.selectUserType('Admin')
        time.sleep(1)
        login.enterEmail('moeez@gmail.com')
        time.sleep(1)
        login.enterPassword('1234')
        time.sleep(1)
        login.signInClick()
        time.sleep(1)
        admin=AdminPage(driver)
        admin.selectApprove()
        time.sleep(1)
        admin.logout()
        time.sleep(1)

#if __name__=='__main__':
    #unittest.main()
